### ISSUE TITLE
Generic usage example :)

### ISSUE THREAD

**Issue by kristianmandrup** [letsrock-today/mock-local-storage#6]
Your example only shows how to use it from `mocha` via `-r` option

I'm trying to do the following from node (ava unit test)

```js
global.window = {}

import localStorage from 'mock-local-storage'

test('Mock localStorage', t => {
  window.localStorage = localStorage
  // ...
})
```

But I get error: `getItem is not a function`.

Ah, but looking at the code I see:

```js
(function(glob) {
  // adds to glob
}(typeof window !== 'undefined' ? window : global));
```

This actually works!!

```js
global.window = {}
import localStorage from 'mock-local-storage'

test('Mock localStorage', t => {
  window.localStorage = global.localStorage
```

And even works if I put it in a separate file and do:

`mock-localstorage.js`

```js
global.window = {}
import localStorage from 'mock-local-storage'
window.localStorage = global.localStorage
```

`import './mock-localstorage'`

A nice little recipe that could be added to the Readme!

**Comment by nikolay-turpitko** [comment]
Hi Kristian,

Thanks for your example. Honestly, it's been quite a time since I used this code myself and now I hardly understand what you are asking for.

If you'd like to make it more useful for others, could you please make a PR?

BTW, I'm looking for someone to take care of this project. Someone, who currently regularly use it and have fresh JS experience.

**Comment by nikolay-turpitko** [comment]
Thank you very much, Kristian! PR #7 merged.
