### ISSUE TITLE
XMLHttpRequest doesn't work after upgrading

### ISSUE THREAD

**Issue by henri-hulski** [letsrock-today/mock-local-storage#9]
After upgrading mock-local-storage from version 1.0.2 to version 1.0.4 `XMLHttpRequest` isn't available anymore during tests.
`XMLHttpRequest` is provided by [xhr-mock](https://github.com/jameslnewell/xhr-mock).
When downgrading mock-local-storage `XMLHttpRequest` works again.

**Comment by nikolay-turpitko** [comment]
Hi @henri-hulski,
Sounds strange to me, because I can't spot any difference in dependencies between versions.
But if you are sure that you find a cause and able to fix and test this, you are welcome to make a PR.
I haven't use  this lib for some time (also I was not much in JS dev recently), so I'm not sure when (if ever) I'll find a time to have a look at it myself.

**Comment by henri-hulski** [comment]
I think it has something to do with cleaning up the global/window scope and removing `XMLHttpRequest`from it. 
Not sure if I'm able to fix it. But when I find the time I will look into it.
